name: Go
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Test with Go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.17, 1.18, 1.19]
        os: [ubuntu-20.04, macOS-latest]
    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Run Unit Tests
      run: ./scripts/runUnitTests.sh
